// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjIU0hPI3ytbipKhIMdmB6WRpCtB97pSY',
    appId: '1:308506417436:web:6636540013c6e7f60c02d9',
    messagingSenderId: '308506417436',
    projectId: 'ecommercetest-26a76',
    authDomain: 'ecommercetest-26a76.firebaseapp.com',
    storageBucket: 'ecommercetest-26a76.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA-5bLkDmoYxgdqfvRAOXG_8iQX0aYefA',
    appId: '1:308506417436:android:124e20438eebb6a30c02d9',
    messagingSenderId: '308506417436',
    projectId: 'ecommercetest-26a76',
    storageBucket: 'ecommercetest-26a76.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAApnBfAZ9WAkwwXDqvKobHIhI3D87QdXk',
    appId: '1:308506417436:ios:e8d1a5b6596fde500c02d9',
    messagingSenderId: '308506417436',
    projectId: 'ecommercetest-26a76',
    storageBucket: 'ecommercetest-26a76.appspot.com',
    iosClientId: '308506417436-ht965e88crh6qpii76vqovflk7d9q0bp.apps.googleusercontent.com',
    iosBundleId: 'com.prateekrathore.flutterHelloWorld',
  );
}
